/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    pages: Page;
    services: Service;
    projects: Project;
    categories: Category;
    posts: Post;
    documents: Document;
    team: Team;
    partners: Partner;
    inquiries: Inquiry;
    media: Media;
    users: User;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    pages: PagesSelect<false> | PagesSelect<true>;
    services: ServicesSelect<false> | ServicesSelect<true>;
    projects: ProjectsSelect<false> | ProjectsSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    posts: PostsSelect<false> | PostsSelect<true>;
    documents: DocumentsSelect<false> | DocumentsSelect<true>;
    team: TeamSelect<false> | TeamSelect<true>;
    partners: PartnersSelect<false> | PartnersSelect<true>;
    inquiries: InquiriesSelect<false> | InquiriesSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: ('false' | 'none' | 'null') | false | null | ('vi' | 'en') | ('vi' | 'en')[];
  globals: {
    header: Header;
    footer: Footer;
    'site-settings': SiteSetting;
  };
  globalsSelect: {
    header: HeaderSelect<false> | HeaderSelect<true>;
    footer: FooterSelect<false> | FooterSelect<true>;
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
  };
  locale: 'vi' | 'en';
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  /**
   * Ví dụ: "home" cho trang chủ, "about" cho giới thiệu, "contact" cho liên hệ
   */
  slug: string;
  layout?:
    | (
        | {
            badgeText?: string | null;
            titleLine1: string;
            titleLine2: string;
            description?: string | null;
            primaryCta?: {
              label?: string | null;
              url?: string | null;
            };
            secondaryCta?: {
              label?: string | null;
              url?: string | null;
            };
            backgroundImage?: (number | null) | Media;
            statsCard?: {
              headerTitle?: string | null;
              statAValue?: string | null;
              statALabel?: string | null;
              statBValue?: string | null;
              statBLabel?: string | null;
              dossierLinkText?: string | null;
              dossierLinkUrl?: string | null;
              footnote?: string | null;
            };
            tickerItems?:
              | {
                  text: string;
                  highlight?: string | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'hero';
          }
        | {
            badge?: string | null;
            heading?: string | null;
            features?:
              | {
                  title: string;
                  description: string;
                  icon?: ('shield' | 'qrcode' | 'chart' | 'check') | null;
                  id?: string | null;
                }[]
              | null;
            teamCard?: {
              title?: string | null;
              description?: string | null;
              buttonText?: string | null;
              buttonUrl?: string | null;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'whyUs';
          }
        | {
            badge?: string | null;
            heading?: string | null;
            description?: string | null;
            steps?:
              | {
                  stepNumber: string;
                  title: string;
                  description: string;
                  badgeText?: string | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'process';
          }
        | {
            badge?: string | null;
            heading?: string | null;
            description?: string | null;
            servicesMode?: ('dynamic' | 'manual') | null;
            selectedServices?: (number | Service)[] | null;
            bottomCta?: {
              title?: string | null;
              buttonText?: string | null;
              buttonUrl?: string | null;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'servicesBlock';
          }
        | {
            badge?: string | null;
            heading?: string | null;
            description?: string | null;
            portals?:
              | {
                  tag: string;
                  title: string;
                  description: string;
                  actionLabel: string;
                  actionUrl: string;
                  icon?: ('file' | 'qr' | 'portal') | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'partnerPortal';
          }
        | {
            badge?: string | null;
            heading?: string | null;
            description?: string | null;
            limit?: number | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'partnersBlock';
          }
        | {
            badge?: string | null;
            heading?: string | null;
            description?: string | null;
            categoryChips?:
              | {
                  name: string;
                  slug?: string | null;
                  id?: string | null;
                }[]
              | null;
            viewAllText?: string | null;
            viewAllUrl?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'insightsBlock';
          }
        | {
            badge?: string | null;
            heading?: string | null;
            items?:
              | {
                  quote: string;
                  clientTitle?: string | null;
                  companyType?: string | null;
                  avatar?: (number | null) | Media;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'testimonials';
          }
        | {
            badge?: string | null;
            heading?: string | null;
            description?: string | null;
            buttonLabel?: string | null;
            buttonUrl?: string | null;
            hotlineLabel?: string | null;
            hotlineNumber?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'ctaBanner';
          }
        | {
            title?: string | null;
            content: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'richContent';
          }
        | {
            heading?: string | null;
            items?:
              | {
                  question: string;
                  answer: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'faq';
          }
      )[]
    | null;
  metaTitle?: string | null;
  metaDescription?: string | null;
  ogImage?: (number | null) | Media;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt?: string | null;
  caption?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services".
 */
export interface Service {
  id: number;
  title: string;
  slug: string;
  order?: number | null;
  icon?: ('building' | 'realestate' | 'machinery' | 'brand' | 'project' | 'finance') | null;
  shortDescription: string;
  coverImage?: (number | null) | Media;
  valuationPurposes?:
    | {
        title: string;
        description?: string | null;
        id?: string | null;
      }[]
    | null;
  processSteps?:
    | {
        step: string;
        title: string;
        description?: string | null;
        id?: string | null;
      }[]
    | null;
  requiredDossier?:
    | {
        documentName: string;
        isMandatory?: boolean | null;
        id?: string | null;
      }[]
    | null;
  legalStandards?:
    | {
        code: string;
        name: string;
        id?: string | null;
      }[]
    | null;
  detailedContent?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects".
 */
export interface Project {
  id: number;
  title: string;
  category: 'doanh-nghiep' | 'bat-dong-san' | 'ha-tang' | 'may-thiet-bi' | 'tai-san-vo-hinh' | 'du-an';
  client?: string | null;
  valuationPurpose?: string | null;
  scale?: string | null;
  year?: number | null;
  coverImage?: (number | null) | Media;
  caseStudyContent?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  name: string;
  slug: string;
  description?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: number;
  title: string;
  slug: string;
  category: number | Category;
  publishedAt?: string | null;
  summary: string;
  coverImage?: (number | null) | Media;
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  readingTime?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "documents".
 */
export interface Document {
  id: number;
  title: string;
  docNumber: string;
  type?: ('license' | 'standard' | 'procedure' | 'policy' | 'profile') | null;
  issuingAuthority?: string | null;
  effectiveDate?: string | null;
  summary?: string | null;
  fileAttachment?: (number | null) | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "team".
 */
export interface Team {
  id: number;
  name: string;
  position: string;
  experienceYears?: number | null;
  category: 'leadership' | 'valuer';
  order?: number | null;
  avatar?: (number | null) | Media;
  /**
   * Mô tả quá trình công tác, bằng cấp, năng lực chuyên môn của nhân sự
   */
  bio?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "partners".
 */
export interface Partner {
  id: number;
  name: string;
  logo?: (number | null) | Media;
  /**
   * Dùng nếu chưa tải file lên Media library (VD: /assets/partners/vcb.svg)
   */
  logoSvg?: string | null;
  category: 'bank' | 'corporate' | 'public' | 'investor' | 'audit';
  website?: string | null;
  order?: number | null;
  active?: boolean | null;
  featured?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "inquiries".
 */
export interface Inquiry {
  id: number;
  ticketNumber?: string | null;
  dossierType?: ('request' | 'quote' | 'recruitment' | 'general') | null;
  fullName: string;
  phone: string;
  email?: string | null;
  organization?: string | null;
  serviceType?:
    | (
        | 'doanh-nghiep'
        | 'Dich-vu-Doanh-nghiep'
        | 'bat-dong-san'
        | 'Dich-vu-Bat-dong-san'
        | 'may-thiet-bi'
        | 'Dich-vu-May-thiet-bi'
        | 'tai-san-vo-hinh'
        | 'Dich-vu-Thuong-hieu'
        | 'du-an'
        | 'Dich-vu-Du-an-dau-tu'
        | 'chung-minh-tai-chinh'
        | 'Dich-vu-Chung-minh-tai-chinh'
        | 'recruitment'
        | 'khac'
      )
    | null;
  attachment?: (number | null) | Media;
  fileName?: string | null;
  fileUrl?: string | null;
  fileSize?: string | null;
  message?: string | null;
  notes?: string | null;
  status?: ('new' | 'in_progress' | 'quoted' | 'completed') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name: string;
  roles: ('admin' | 'editor')[];
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  resetPasswordRequestedAt?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'services';
        value: number | Service;
      } | null)
    | ({
        relationTo: 'projects';
        value: number | Project;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'posts';
        value: number | Post;
      } | null)
    | ({
        relationTo: 'documents';
        value: number | Document;
      } | null)
    | ({
        relationTo: 'team';
        value: number | Team;
      } | null)
    | ({
        relationTo: 'partners';
        value: number | Partner;
      } | null)
    | ({
        relationTo: 'inquiries';
        value: number | Inquiry;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  layout?:
    | T
    | {
        hero?:
          | T
          | {
              badgeText?: T;
              titleLine1?: T;
              titleLine2?: T;
              description?: T;
              primaryCta?:
                | T
                | {
                    label?: T;
                    url?: T;
                  };
              secondaryCta?:
                | T
                | {
                    label?: T;
                    url?: T;
                  };
              backgroundImage?: T;
              statsCard?:
                | T
                | {
                    headerTitle?: T;
                    statAValue?: T;
                    statALabel?: T;
                    statBValue?: T;
                    statBLabel?: T;
                    dossierLinkText?: T;
                    dossierLinkUrl?: T;
                    footnote?: T;
                  };
              tickerItems?:
                | T
                | {
                    text?: T;
                    highlight?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        whyUs?:
          | T
          | {
              badge?: T;
              heading?: T;
              features?:
                | T
                | {
                    title?: T;
                    description?: T;
                    icon?: T;
                    id?: T;
                  };
              teamCard?:
                | T
                | {
                    title?: T;
                    description?: T;
                    buttonText?: T;
                    buttonUrl?: T;
                  };
              id?: T;
              blockName?: T;
            };
        process?:
          | T
          | {
              badge?: T;
              heading?: T;
              description?: T;
              steps?:
                | T
                | {
                    stepNumber?: T;
                    title?: T;
                    description?: T;
                    badgeText?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        servicesBlock?:
          | T
          | {
              badge?: T;
              heading?: T;
              description?: T;
              servicesMode?: T;
              selectedServices?: T;
              bottomCta?:
                | T
                | {
                    title?: T;
                    buttonText?: T;
                    buttonUrl?: T;
                  };
              id?: T;
              blockName?: T;
            };
        partnerPortal?:
          | T
          | {
              badge?: T;
              heading?: T;
              description?: T;
              portals?:
                | T
                | {
                    tag?: T;
                    title?: T;
                    description?: T;
                    actionLabel?: T;
                    actionUrl?: T;
                    icon?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        partnersBlock?:
          | T
          | {
              badge?: T;
              heading?: T;
              description?: T;
              limit?: T;
              id?: T;
              blockName?: T;
            };
        insightsBlock?:
          | T
          | {
              badge?: T;
              heading?: T;
              description?: T;
              categoryChips?:
                | T
                | {
                    name?: T;
                    slug?: T;
                    id?: T;
                  };
              viewAllText?: T;
              viewAllUrl?: T;
              id?: T;
              blockName?: T;
            };
        testimonials?:
          | T
          | {
              badge?: T;
              heading?: T;
              items?:
                | T
                | {
                    quote?: T;
                    clientTitle?: T;
                    companyType?: T;
                    avatar?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        ctaBanner?:
          | T
          | {
              badge?: T;
              heading?: T;
              description?: T;
              buttonLabel?: T;
              buttonUrl?: T;
              hotlineLabel?: T;
              hotlineNumber?: T;
              id?: T;
              blockName?: T;
            };
        richContent?:
          | T
          | {
              title?: T;
              content?: T;
              id?: T;
              blockName?: T;
            };
        faq?:
          | T
          | {
              heading?: T;
              items?:
                | T
                | {
                    question?: T;
                    answer?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
      };
  metaTitle?: T;
  metaDescription?: T;
  ogImage?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services_select".
 */
export interface ServicesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  order?: T;
  icon?: T;
  shortDescription?: T;
  coverImage?: T;
  valuationPurposes?:
    | T
    | {
        title?: T;
        description?: T;
        id?: T;
      };
  processSteps?:
    | T
    | {
        step?: T;
        title?: T;
        description?: T;
        id?: T;
      };
  requiredDossier?:
    | T
    | {
        documentName?: T;
        isMandatory?: T;
        id?: T;
      };
  legalStandards?:
    | T
    | {
        code?: T;
        name?: T;
        id?: T;
      };
  detailedContent?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects_select".
 */
export interface ProjectsSelect<T extends boolean = true> {
  title?: T;
  category?: T;
  client?: T;
  valuationPurpose?: T;
  scale?: T;
  year?: T;
  coverImage?: T;
  caseStudyContent?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  description?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  category?: T;
  publishedAt?: T;
  summary?: T;
  coverImage?: T;
  content?: T;
  readingTime?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "documents_select".
 */
export interface DocumentsSelect<T extends boolean = true> {
  title?: T;
  docNumber?: T;
  type?: T;
  issuingAuthority?: T;
  effectiveDate?: T;
  summary?: T;
  fileAttachment?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "team_select".
 */
export interface TeamSelect<T extends boolean = true> {
  name?: T;
  position?: T;
  experienceYears?: T;
  category?: T;
  order?: T;
  avatar?: T;
  bio?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "partners_select".
 */
export interface PartnersSelect<T extends boolean = true> {
  name?: T;
  logo?: T;
  logoSvg?: T;
  category?: T;
  website?: T;
  order?: T;
  active?: T;
  featured?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "inquiries_select".
 */
export interface InquiriesSelect<T extends boolean = true> {
  ticketNumber?: T;
  dossierType?: T;
  fullName?: T;
  phone?: T;
  email?: T;
  organization?: T;
  serviceType?: T;
  attachment?: T;
  fileName?: T;
  fileUrl?: T;
  fileSize?: T;
  message?: T;
  notes?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  roles?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  resetPasswordRequestedAt?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header".
 */
export interface Header {
  id: number;
  logo?: (number | null) | Media;
  navItems?:
    | {
        title: string;
        menuKey?: ('about' | 'services' | 'projects' | 'insight' | 'legal' | 'contact' | 'single') | null;
        href?: string | null;
        tagline?: string | null;
        subItems?:
          | {
              title: string;
              description?: string | null;
              href: string;
              id?: string | null;
            }[]
          | null;
        ctaCard?: {
          tag?: string | null;
          title?: string | null;
          description?: string | null;
          buttonLabel?: string | null;
          buttonHref?: string | null;
        };
        id?: string | null;
      }[]
    | null;
  verifyButton?: {
    show?: boolean | null;
    label?: string | null;
    href?: string | null;
  };
  requestButton?: {
    label?: string | null;
    href?: string | null;
  };
  phone?: string | null;
  licenseNotice?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: number;
  companyName?: string | null;
  tagline?: string | null;
  qualificationNotice?: string | null;
  address?: string | null;
  phone?: string | null;
  email?: string | null;
  workingHours?: string | null;
  columns?:
    | {
        title: string;
        links?:
          | {
              label: string;
              href: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  licenseText?: string | null;
  copyright?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  siteName: string;
  defaultSeoDescription?: string | null;
  socialLinks?:
    | {
        platform: string;
        url: string;
        id?: string | null;
      }[]
    | null;
  hotline?: string | null;
  zaloNumber?: string | null;
  zaloUrl?: string | null;
  workingHours?: string | null;
  quickContactTitle?: string | null;
  phoneTitle?: string | null;
  zaloTitle?: string | null;
  officeCompany?: string | null;
  officeAddress?: string | null;
  officeHoursWeekday?: string | null;
  officeHoursWeekend?: string | null;
  officePhone?: string | null;
  officeEmail?: string | null;
  officeMapUrl?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header_select".
 */
export interface HeaderSelect<T extends boolean = true> {
  logo?: T;
  navItems?:
    | T
    | {
        title?: T;
        menuKey?: T;
        href?: T;
        tagline?: T;
        subItems?:
          | T
          | {
              title?: T;
              description?: T;
              href?: T;
              id?: T;
            };
        ctaCard?:
          | T
          | {
              tag?: T;
              title?: T;
              description?: T;
              buttonLabel?: T;
              buttonHref?: T;
            };
        id?: T;
      };
  verifyButton?:
    | T
    | {
        show?: T;
        label?: T;
        href?: T;
      };
  requestButton?:
    | T
    | {
        label?: T;
        href?: T;
      };
  phone?: T;
  licenseNotice?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  companyName?: T;
  tagline?: T;
  qualificationNotice?: T;
  address?: T;
  phone?: T;
  email?: T;
  workingHours?: T;
  columns?:
    | T
    | {
        title?: T;
        links?:
          | T
          | {
              label?: T;
              href?: T;
              id?: T;
            };
        id?: T;
      };
  licenseText?: T;
  copyright?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  siteName?: T;
  defaultSeoDescription?: T;
  socialLinks?:
    | T
    | {
        platform?: T;
        url?: T;
        id?: T;
      };
  hotline?: T;
  zaloNumber?: T;
  zaloUrl?: T;
  workingHours?: T;
  quickContactTitle?: T;
  phoneTitle?: T;
  zaloTitle?: T;
  officeCompany?: T;
  officeAddress?: T;
  officeHoursWeekday?: T;
  officeHoursWeekend?: T;
  officePhone?: T;
  officeEmail?: T;
  officeMapUrl?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}