export interface ProjectData {
  id: string | number
  title: string
  category: string
  client?: string
  valuationPurpose?: string
  scale?: string
  year?: number
  image?: string
  location?: string
  highlights?: string[]
}

export const DEFAULT_PROJECTS: { vi: ProjectData[]; en: ProjectData[] } = {
  vi: [
    {
      id: 'p1',
      title: 'Thẩm định giá trị doanh nghiệp phục vụ tái cấu trúc vốn và M&A — Tập đoàn Năng lượng tái tạo & Hạ tầng',
      category: 'doanh-nghiep',
      client: 'Tập đoàn Năng lượng tư nhân hàng đầu',
      valuationPurpose: 'Phát hành cổ phần chiến lược & Tái cấu trúc vốn vay ngân hàng',
      scale: '12.800 Tỷ VNĐ',
      year: 2025,
      location: 'TP. Hồ Chí Minh & Bình Thuận',
      image: 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?q=80&w=800&auto=format&fit=crop',
      highlights: ['Phương pháp DCF & Định giá so sánh P/E, EV/EBITDA', 'Kiểm toán Big4 phê duyệt báo cáo độc lập'],
    },
    {
      id: 'p2',
      title: 'Xác định giá trị tài sản vô hình và thương hiệu chuỗi bán lẻ tiêu dùng đa kênh toàn quốc',
      category: 'tai-san-vo-hinh',
      client: 'Hệ thống Bán lẻ & F&B quy mô 200+ điểm',
      valuationPurpose: 'Góp vốn liên doanh và lập báo cáo tài chính quốc tế (IFRS)',
      scale: '3.450 Tỷ VNĐ',
      year: 2024,
      location: 'Toàn quốc (Hà Nội, Đà Nẵng, TP.HCM)',
      image: 'https://images.unsplash.com/photo-1555421689-491a97ff2040?q=80&w=800&auto=format&fit=crop',
      highlights: ['Phương pháp Relief-from-Royalty (Chiết trừ bản quyền)', 'Được Hội đồng quản trị & Đối tác nước ngoài thông qua'],
    },
    {
      id: 'p3',
      title: 'Thẩm định giá trị quyền sử dụng đất & tài sản gắn liền — Khu đô thị sinh thái 120 ha',
      category: 'bat-dong-san',
      client: 'Chủ đầu tư Bất động sản Top 3 Việt Nam',
      valuationPurpose: 'Bảo đảm phát hành trái phiếu doanh nghiệp & Tài trợ dự án ngân hàng',
      scale: '28.500 Tỷ VNĐ',
      year: 2025,
      location: 'Đồng Nai (Khu đô thị vệ tinh TP.HCM)',
      image: 'https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?q=80&w=800&auto=format&fit=crop',
      highlights: ['Phương pháp Thặng dư quy hoạch 1/500 chi tiết', 'Tài sản bảo đảm phát hành thành công 5.000 Tỷ trái phiếu'],
    },
    {
      id: 'p4',
      title: 'Định giá Tòa nhà văn phòng thương mại Hạng A và TTTM phức hợp trung tâm TP.HCM',
      category: 'bat-dong-san',
      client: 'Quỹ đầu tư Bất động sản khu vực Đông Nam Á',
      valuationPurpose: 'Thực hiện giao dịch chuyển nhượng vốn (M&A Real Estate)',
      scale: '8.200 Tỷ VNĐ',
      year: 2024,
      location: 'Quận 1, TP. Hồ Chí Minh',
      image: 'https://images.unsplash.com/photo-1497366216548-37526070297c?q=80&w=800&auto=format&fit=crop',
      highlights: ['Tỷ suất vốn hóa (Cap Rate) 6.8%', 'Chuẩn mực thẩm định quốc tế RICS song song TĐGVN'],
    },
    {
      id: 'p5',
      title: 'Thẩm định giá trị dây chuyền công nghệ & Tổ hợp nhà máy sản xuất linh kiện bán dẫn',
      category: 'ha-tang',
      client: 'Doanh nghiệp FDI công nghệ cao',
      valuationPurpose: 'Thế chấp hạn mức tín dụng tài trợ máy móc thiết bị nhập khẩu',
      scale: '4.750 Tỷ VNĐ',
      year: 2025,
      location: 'Khu công nghệ cao TP.HCM (SHTP)',
      image: 'https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?q=80&w=800&auto=format&fit=crop',
      highlights: ['Khảo sát thực địa chi tiết 1.200 danh mục thiết bị', 'Ngân hàng ngoại giải ngân 100% hạn mức cam kết'],
    },
    {
      id: 'p6',
      title: 'Thẩm định tài sản kết cấu hạ tầng cảng biển tổng hợp & Hệ thống kho bãi logistics nước sâu',
      category: 'ha-tang',
      client: 'Công ty Cổ phần Cảng biển Quốc tế',
      valuationPurpose: 'Đánh giá lại tài sản phục vụ cổ phần hóa và liên kết chiến lược',
      scale: '9.600 Tỷ VNĐ',
      year: 2024,
      location: 'Cụm cảng Cái Mép — Thị Vải, Bà Rịa - Vũng Tàu',
      image: 'https://images.unsplash.com/photo-1578575437130-527eed3abbec?q=80&w=800&auto=format&fit=crop',
      highlights: ['Cầu cảng đón tàu 160.000 DWT', 'Phục vụ đề án tái cơ cấu doanh nghiệp Nhà nước'],
    },
    {
      id: 'p7',
      title: 'Thẩm định giá tổ hợp máy biến áp, trạm truyền tải và turbine điện gió ngoài khơi 150MW',
      category: 'may-thiet-bi',
      client: 'Chủ đầu tư Năng lượng sạch Quốc tế',
      valuationPurpose: 'Bảo hiểm kỹ thuật công trình & Giải ngân vốn tín dụng xanh ODA',
      scale: '6.300 Tỷ VNĐ',
      year: 2024,
      location: 'Trà Vinh — Bến Tre',
      image: 'https://images.unsplash.com/photo-1466611653911-95081537e5b7?q=80&w=800&auto=format&fit=crop',
      highlights: ['Đánh giá hao mòn trong môi trường biển mặn', 'Hồ sơ thẩm định đáp ứng điều kiện khắt khe của tổ chức ODA'],
    },
    {
      id: 'p8',
      title: 'Thẩm định giá dây chuyền chiết rót, đóng chai tự động và hệ thống kho lạnh 15.000m²',
      category: 'may-thiet-bi',
      client: 'Tập đoàn Thực phẩm & Đồ uống Quốc tế',
      valuationPurpose: 'Tái tài trợ vốn lưu động & Khấu hao tài sản tài chính',
      scale: '1.850 Tỷ VNĐ',
      year: 2025,
      location: 'KCN VSIP II, Bình Dương',
      image: 'https://images.unsplash.com/photo-1504917599217-d4dc5ebe6122?q=80&w=800&auto=format&fit=crop',
      highlights: ['Dây chuyền nhập khẩu từ Krones CHLB Đức', 'Thẩm định chi phí thay thế ròng DRC chuẩn xác'],
    },
    {
      id: 'p9',
      title: 'Thẩm định giá trị phần mềm quản trị ERP độc quyền và bản quyền sáng chế công nghệ xử lý dữ liệu lớn',
      category: 'tai-san-vo-hinh',
      client: 'Công ty Cổ phần Công nghệ Điện toán đám mây',
      valuationPurpose: 'Huy động vốn vòng Series B & Báo cáo cổ đông ngoại',
      scale: '920 Tỷ VNĐ',
      year: 2025,
      location: 'Công viên Phần mềm Quang Trung, TP.HCM',
      image: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?q=80&w=800&auto=format&fit=crop',
      highlights: ['Mô hình Excess Earnings Method (Lợi nhuận vượt trội)', 'Huy động thành công 25M USD từ Venture Capital'],
    },
    {
      id: 'p10',
      title: 'Định giá Cụm hạ tầng Khu công nghiệp sinh thái kỹ thuật cao quy mô 350 ha',
      category: 'ha-tang',
      client: 'Tổng Công ty Phát triển Đô thị & KCN',
      valuationPurpose: 'Hợp tác liên doanh thu hút vốn đầu tư FDI Nhật Bản',
      scale: '15.400 Tỷ VNĐ',
      year: 2025,
      location: 'Bình Phước — Tây Ninh',
      image: 'https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?q=80&w=800&auto=format&fit=crop',
      highlights: ['Quy hoạch 350 ha đạt tiêu chuẩn xanh Net Zero', 'Đối tác Nhật Bản ký kết hợp đồng góp vốn thành công'],
    },
  ],
  en: [
    {
      id: 'p1',
      title: 'Enterprise Valuation for Capital Restructuring and M&A — Renewable Energy & Infrastructure Group',
      category: 'doanh-nghiep',
      client: 'Leading Private Energy Conglomerate',
      valuationPurpose: 'Strategic Equity Issuance & Syndicated Debt Restructuring',
      scale: '$510M USD',
      year: 2025,
      location: 'Ho Chi Minh City & Binh Thuan',
      image: 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?q=80&w=800&auto=format&fit=crop',
      highlights: ['DCF & Market Multiples (P/E, EV/EBITDA)', 'Big4 audit firm approval for independent valuation'],
    },
    {
      id: 'p2',
      title: 'Valuation of Intangible Assets and Brand Equity for Nationwide Omnichannel Retail Network',
      category: 'tai-san-vo-hinh',
      client: 'National Retail & F&B Network (200+ outlets)',
      valuationPurpose: 'Joint Venture Capital Contribution & IFRS Financial Reporting',
      scale: '$138M USD',
      year: 2024,
      location: 'Nationwide (Hanoi, Da Nang, HCMC)',
      image: 'https://images.unsplash.com/photo-1555421689-491a97ff2040?q=80&w=800&auto=format&fit=crop',
      highlights: ['Relief-from-Royalty Methodology', 'Ratified by Board of Directors and overseas partners'],
    },
    {
      id: 'p3',
      title: 'Valuation of Land Use Rights & Built Assets — 120-hectare Eco-Urban Township Complex',
      category: 'bat-dong-san',
      client: 'Top 3 Real Estate Developer in Vietnam',
      valuationPurpose: 'Corporate Bond Guarantee & Syndicated Bank Construction Financing',
      scale: '$1.14B USD',
      year: 2025,
      location: 'Dong Nai (Greater HCMC Metropolitan Area)',
      image: 'https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?q=80&w=800&auto=format&fit=crop',
      highlights: ['Residual Method on 1/500 Detailed Master Plan', 'Collateral for $200M Corporate Bond Issuance'],
    },
    {
      id: 'p4',
      title: 'Valuation of Grade A Commercial Office Tower & Mixed-use Retail Center in Central HCMC',
      category: 'bat-dong-san',
      client: 'Southeast Asian Real Estate Private Equity Fund',
      valuationPurpose: 'Asset Acquisition & Equity Transfer (M&A Real Estate)',
      scale: '$328M USD',
      year: 2024,
      location: 'District 1, Ho Chi Minh City',
      image: 'https://images.unsplash.com/photo-1497366216548-37526070297c?q=80&w=800&auto=format&fit=crop',
      highlights: ['Cap Rate 6.8% Market Benchmark', 'Dual compliance: RICS & Vietnam Valuation Standards'],
    },
    {
      id: 'p5',
      title: 'Valuation of Tech Manufacturing Lines & Semiconductor Components Production Plant',
      category: 'ha-tang',
      client: 'High-tech FDI Manufacturing Enterprise',
      valuationPurpose: 'Pledge of Imported Machinery & Equipment for Working Capital Facility',
      scale: '$190M USD',
      year: 2025,
      location: 'Saigon Hi-Tech Park (SHTP)',
      image: 'https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?q=80&w=800&auto=format&fit=crop',
      highlights: ['Physical verification of 1,200 asset line items', '100% credit line disbursement by foreign consortium'],
    },
    {
      id: 'p6',
      title: 'Valuation of Deep-water Port Infrastructure & Integrated Logistics Warehousing Complex',
      category: 'ha-tang',
      client: 'International Seaport Joint Stock Company',
      valuationPurpose: 'Asset Revaluation for Equitization and Strategic Investment Alliance',
      scale: '$384M USD',
      year: 2024,
      location: 'Cai Mep — Thi Vai Port Complex',
      image: 'https://images.unsplash.com/photo-1578575437130-527eed3abbec?q=80&w=800&auto=format&fit=crop',
      highlights: ['160,000 DWT vessel handling capacity berths', 'State-owned enterprise restructuring roadmap support'],
    },
    {
      id: 'p7',
      title: 'Valuation of High-Voltage Substations, Transmission Network & 150MW Offshore Wind Turbines',
      category: 'may-thiet-bi',
      client: 'Clean Energy Project Sponsor',
      valuationPurpose: 'Engineering Construction Insurance & ODA Tranche Disbursement',
      scale: '$252M USD',
      year: 2024,
      location: 'Tra Vinh — Ben Tre Offshore Waters',
      image: 'https://images.unsplash.com/photo-1466611653911-95081537e5b7?q=80&w=800&auto=format&fit=crop',
      highlights: ['Marine salinity depreciation analysis', 'Full compliance with international ODA guidelines'],
    },
    {
      id: 'p8',
      title: 'Valuation of Automated Bottling & Filling Production Lines and 15,000m² Cold Storage Complex',
      category: 'may-thiet-bi',
      client: 'Multinational Food & Beverage Conglomerate',
      valuationPurpose: 'Working Capital Refinancing & Financial Asset Depreciation',
      scale: '$74M USD',
      year: 2025,
      location: 'VSIP II Industrial Park, Binh Duong',
      image: 'https://images.unsplash.com/photo-1504917599217-d4dc5ebe6122?q=80&w=800&auto=format&fit=crop',
      highlights: ['German Krones automated packaging lines', 'Depreciated Replacement Cost (DRC) methodology'],
    },
    {
      id: 'p9',
      title: 'Valuation of Proprietary Cloud ERP Platform & Patented Big-Data Processing Algorithms',
      category: 'tai-san-vo-hinh',
      client: 'Enterprise Cloud Computing Corporation',
      valuationPurpose: 'Series B Capital Raise & Foreign Shareholder Reporting',
      scale: '$37M USD',
      year: 2025,
      location: 'Quang Trung Software City, HCMC',
      image: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?q=80&w=800&auto=format&fit=crop',
      highlights: ['Multi-period Excess Earnings Method (MPEEM)', '$25M Series B funding successfully closed'],
    },
    {
      id: 'p10',
      title: 'Valuation of 350-hectare High-Tech Eco-Industrial Park Infrastructure in Southern Key Economic Zone',
      category: 'ha-tang',
      client: 'Industrial & Urban Infrastructure Developer',
      valuationPurpose: 'Joint Venture Structuring for Japanese FDI Inflow',
      scale: '$616M USD',
      year: 2025,
      location: 'Binh Phuoc — Tay Ninh',
      image: 'https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?q=80&w=800&auto=format&fit=crop',
      highlights: ['Net-Zero eco-industrial park planning', 'Formal JV agreement executed with Japanese partners'],
    },
  ],
}
